### PR TITLE
Kanela Support

### PR DESCRIPTION
**Pull request by dpsoft**

### CODE REVIEW

**Comment by ivantopo** [comment]
yo @dpsoft, what's the status of this PR?

**Comment by dpsoft** [comment]
@ivantopo The PR is almost complete, the idea is support both Aspect and Kanela in the same release .. but we need define if this is what we want.

**Comment by dpsoft** [comment]
@ivantopo ping!

**Comment by ivantopo** [comment]
Hey @dpsoft, I'm closing this one because we already have the changes for Kanela coming from another branch. Hopefully I'll be able to finish them this week.

**Pull request closed without merging**
